import { useState, useEffect } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";

import { approveContent, downloadContent, patchContent, rejectContent, type ContentPublic } from "@/lib/api";
import { LinkedInCard } from "./renderers/LinkedInCard";
import { NewsletterPreview } from "./renderers/NewsletterPreview";
import { FlyerPreview } from "./renderers/FlyerPreview";
import { InstagramCard } from "./renderers/InstagramCard";
import { BlogArticle } from "./renderers/BlogArticle";
import { SummaryView } from "./renderers/SummaryView";

interface ContentStudioProps {
  token: string;
  jobId: string;
  pieces: ContentPublic[];
}

const TYPE_CONFIG: Record<string, { label: string; icon: string; desc: string }> = {
  summary: { label: "Summary", icon: "📝", desc: "Executive briefing & key takeaways" },
  blog: { label: "Blog Post", icon: "📰", desc: "Long-form editorial article" },
  linkedin: { label: "LinkedIn", icon: "💼", desc: "Professional social feed post" },
  newsletter: { label: "Newsletter", icon: "📧", desc: "Email template with highlights" },
  ig_caption: { label: "Instagram", icon: "📸", desc: "Visual post caption with tags" },
  flyer: { label: "Flyer Poster", icon: "🎨", desc: "Visual recap poster card" },
};

export function ContentStudio({ token, jobId, pieces }: ContentStudioProps) {
  const queryClient = useQueryClient();
  const [activeType, setActiveType] = useState<string>("summary");
  const [activeLang, setActiveLang] = useState<string>("en");

  // Editing state
  const [isEditing, setIsEditing] = useState(false);
  const [editTitle, setEditTitle] = useState("");
  const [editBody, setEditBody] = useState("");
  const [rejectReason, setRejectReason] = useState("");
  const [showRejectModal, setShowRejectModal] = useState(false);
  const [feedbackMsg, setFeedbackMsg] = useState<string | null>(null);

  // Available types & languages in current pieces
  const availableTypes = Array.from(new Set(pieces.map((p) => p.type)));
  const availableLangs = Array.from(new Set(pieces.map((p) => p.language || "en")));

  // Set initial active type if default not present
  useEffect(() => {
    if (availableTypes.length > 0 && !availableTypes.includes(activeType)) {
      setActiveType(availableTypes[0]);
    }
  }, [availableTypes, activeType]);

  // Current active piece
  const currentPiece = pieces.find(
    (p) => p.type === activeType && (p.language === activeLang || (!p.language && activeLang === "en")),
  ) || pieces.find((p) => p.type === activeType) || pieces[0];

  // Sync edit state when active piece changes
  useEffect(() => {
    if (currentPiece) {
      setEditTitle(currentPiece.title || "");
      setEditBody(currentPiece.body || "");
      setIsEditing(false);
    }
  }, [currentPiece]);

  function notify(msg: string) {
    setFeedbackMsg(msg);
    setTimeout(() => setFeedbackMsg(null), 3000);
  }

  // Mutations
  const approveMutation = useMutation({
    mutationFn: (id: string) => approveContent(token, id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["content", jobId] });
      queryClient.invalidateQueries({ queryKey: ["job", jobId] });
      notify("✓ Content marked as Approved!");
    },
  });

  const rejectMutation = useMutation({
    mutationFn: ({ id, reason }: { id: string; reason: string }) => rejectContent(token, id, reason),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["content", jobId] });
      queryClient.invalidateQueries({ queryKey: ["job", jobId] });
      setShowRejectModal(false);
      setRejectReason("");
      notify("Content rejected.");
    },
  });

  const saveMutation = useMutation({
    mutationFn: () =>
      patchContent(token, currentPiece!.id, {
        title: editTitle,
        body: editBody,
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["content", jobId] });
      setIsEditing(false);
      notify("✓ Draft changes saved!");
    },
  });

  if (!pieces || pieces.length === 0) {
    return (
      <div className="rounded-card border border-dashed border-primary/30 p-34 text-center">
        <p className="text-sm opacity-60">Content is being generated by the pipeline...</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-21">
      {/* Toast Notification */}
      {feedbackMsg && (
        <div className="fixed bottom-21 right-21 z-50 rounded-card bg-primary px-21 py-13 text-sm font-medium text-white shadow-xl">
          {feedbackMsg}
        </div>
      )}

      {/* Content Type Tabs */}
      <div className="flex flex-wrap items-center justify-between gap-13 border-b border-black/10 pb-13 dark:border-white/10">
        <div className="flex flex-wrap gap-8">
          {availableTypes.map((type) => {
            const config = TYPE_CONFIG[type] || { label: type, icon: "📄", desc: "" };
            const isActive = activeType === type;
            const piece = pieces.find((p) => p.type === type);
            const isApproved = piece?.status === "approved";
            const isPending = piece?.status === "pending_review";

            return (
              <button
                key={type}
                type="button"
                onClick={() => setActiveType(type)}
                className={`flex items-center gap-8 rounded-card px-13 py-8 text-sm font-medium transition-all ${
                  isActive
                    ? "bg-primary text-white shadow-md"
                    : "bg-surface-light text-ink-light hover:bg-black/5 dark:bg-surface-dark dark:text-ink-dark dark:hover:bg-white/5"
                }`}
              >
                <span>{config.icon}</span>
                <span>{config.label}</span>
                {isApproved && <span className="text-xs text-success">✓</span>}
                {isPending && <span className="h-2 w-2 rounded-full bg-accent animate-pulse"></span>}
              </button>
            );
          })}
        </div>

        {/* Language Tabs if multiple */}
        {availableLangs.length > 1 && (
          <div className="flex items-center gap-4 text-xs">
            <span className="opacity-60">Lang:</span>
            {availableLangs.map((lang) => (
              <button
                key={lang}
                type="button"
                onClick={() => setActiveLang(lang)}
                className={`rounded px-8 py-4 font-semibold uppercase ${
                  activeLang === lang
                    ? "bg-accent text-canvas-dark"
                    : "bg-surface-light opacity-70 dark:bg-surface-dark"
                }`}
              >
                {lang}
              </button>
            ))}
          </div>
        )}
      </div>

      {currentPiece && (
        <>
          {/* Action Toolbar */}
          <div className="flex flex-wrap items-center justify-between gap-13 rounded-card bg-surface-light p-13 dark:bg-surface-dark">
            <div className="flex items-center gap-13">
              <span
                className={`rounded-full px-13 py-4 text-xs font-semibold uppercase tracking-wider ${
                  currentPiece.status === "approved"
                    ? "bg-success/15 text-success"
                    : currentPiece.status === "rejected"
                    ? "bg-danger/15 text-danger"
                    : "bg-accent/15 text-accent"
                }`}
              >
                Status: {currentPiece.status.replace("_", " ")}
              </span>

              {isEditing ? (
                <span className="text-xs text-warning">● Editing Draft</span>
              ) : (
                <span className="text-xs opacity-60">v{currentPiece.version || 1}</span>
              )}
            </div>

            {/* Action Buttons */}
            <div className="flex flex-wrap items-center gap-8">
              {/* Edit / View Toggle */}
              {isEditing ? (
                <>
                  <button
                    type="button"
                    onClick={() => saveMutation.mutate()}
                    disabled={saveMutation.isPending}
                    className="rounded-card bg-accent px-13 py-8 text-xs font-semibold text-canvas-dark hover:opacity-90"
                  >
                    {saveMutation.isPending ? "Saving..." : "💾 Save Changes"}
                  </button>
                  <button
                    type="button"
                    onClick={() => setIsEditing(false)}
                    className="rounded-card bg-black/5 px-13 py-8 text-xs font-medium dark:bg-white/5"
                  >
                    Cancel
                  </button>
                </>
              ) : (
                <button
                  type="button"
                  onClick={() => setIsEditing(true)}
                  className="rounded-card border border-black/10 bg-canvas-light px-13 py-8 text-xs font-medium hover:border-primary dark:border-white/10 dark:bg-canvas-dark"
                >
                  ✏️ Edit Copy
                </button>
              )}

              {/* Download Buttons */}
              <button
                type="button"
                onClick={() =>
                  downloadContent(
                    token,
                    currentPiece.id,
                    currentPiece.type === "flyer" ? "json" : "markdown",
                    `${currentPiece.type}_recap`,
                  )
                }
                className="rounded-card border border-black/10 bg-canvas-light px-13 py-8 text-xs font-medium hover:border-primary dark:border-white/10 dark:bg-canvas-dark"
              >
                📥 Download
              </button>

              {/* Human Approval Gate */}
              {currentPiece.status === "pending_review" && (
                <>
                  <button
                    type="button"
                    onClick={() => approveMutation.mutate(currentPiece.id)}
                    disabled={approveMutation.isPending}
                    className="rounded-card bg-success px-13 py-8 text-xs font-semibold text-white hover:opacity-90 shadow"
                  >
                    {approveMutation.isPending ? "Approving..." : "✓ Approve"}
                  </button>
                  <button
                    type="button"
                    onClick={() => setShowRejectModal(true)}
                    className="rounded-card bg-danger/20 px-13 py-8 text-xs font-semibold text-danger hover:bg-danger/30"
                  >
                    ✕ Reject
                  </button>
                </>
              )}
            </div>
          </div>

          {/* Grounding / Moderation Alerts */}
          {currentPiece.grounding && currentPiece.grounding.pass === false && (
            <div className="rounded-card border border-warning/30 bg-warning/10 p-13 text-xs text-warning">
              <p className="font-semibold">⚠️ Grounding Alert: Potential unsupported claim detected</p>
              <ul className="mt-4 list-disc pl-21 opacity-90">
                {(currentPiece.grounding.unsupported || []).slice(0, 3).map((item, i) => (
                  <li key={i}>{item}</li>
                ))}
              </ul>
            </div>
          )}

          {currentPiece.moderation && currentPiece.moderation.pass === false && (
            <div className="rounded-card border border-danger/30 bg-danger/10 p-13 text-xs text-danger">
              ⚠️ Moderation Flag: Output triggered keyword review:{" "}
              {(currentPiece.moderation.hits || []).join(", ")}
            </div>
          )}

          {/* Main Display Area: Editor or Rich Previewer */}
          <div className="flex justify-center">
            {isEditing ? (
              <div className="w-full max-w-3xl rounded-card border border-primary/30 bg-surface-light p-21 shadow-lg dark:bg-surface-dark">
                <label className="block text-xs font-semibold uppercase opacity-60">Title / Headline</label>
                <input
                  type="text"
                  value={editTitle}
                  onChange={(e) => setEditTitle(e.target.value)}
                  className="mt-4 w-full rounded-card border border-black/10 bg-canvas-light px-13 py-8 text-sm dark:border-white/10 dark:bg-canvas-dark"
                  placeholder="Enter title..."
                />

                <label className="mt-21 block text-xs font-semibold uppercase opacity-60">Content Body</label>
                <textarea
                  rows={14}
                  value={editBody}
                  onChange={(e) => setEditBody(e.target.value)}
                  className="mt-4 w-full rounded-card border border-black/10 bg-canvas-light p-13 text-sm font-sans leading-relaxed dark:border-white/10 dark:bg-canvas-dark"
                  placeholder="Enter content..."
                />

                <div className="mt-13 flex justify-between text-xs opacity-60">
                  <span>Words: {editBody.trim() ? editBody.trim().split(/\s+/).length : 0}</span>
                  <span>Characters: {editBody.length}</span>
                </div>
              </div>
            ) : (
              /* Specialized Rich Renderer */
              <>
                {currentPiece.type === "linkedin" && (
                  <LinkedInCard
                    title={currentPiece.title}
                    body={currentPiece.body}
                    onCopy={() => notify("✓ Copied to clipboard!")}
                  />
                )}
                {currentPiece.type === "newsletter" && (
                  <NewsletterPreview
                    title={currentPiece.title}
                    body={currentPiece.body}
                    onCopy={() => notify("✓ Copied to clipboard!")}
                  />
                )}
                {currentPiece.type === "flyer" && (
                  <FlyerPreview
                    title={currentPiece.title}
                    body={currentPiece.body}
                    structured={currentPiece.structured}
                    onCopy={() => notify("✓ Copied to clipboard!")}
                  />
                )}
                {currentPiece.type === "ig_caption" && (
                  <InstagramCard
                    title={currentPiece.title}
                    body={currentPiece.body}
                    onCopy={() => notify("✓ Copied to clipboard!")}
                  />
                )}
                {currentPiece.type === "blog" && (
                  <BlogArticle
                    title={currentPiece.title}
                    body={currentPiece.body}
                    onCopy={() => notify("✓ Copied to clipboard!")}
                  />
                )}
                {currentPiece.type === "summary" && (
                  <SummaryView
                    title={currentPiece.title}
                    body={currentPiece.body}
                    onCopy={() => notify("✓ Copied to clipboard!")}
                  />
                )}
              </>
            )}
          </div>
        </>
      )}

      {/* Reject Modal Dialog */}
      {showRejectModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-21 backdrop-blur-sm">
          <div className="w-full max-w-md rounded-card bg-surface-light p-21 shadow-2xl dark:bg-surface-dark">
            <h3 className="font-display text-h3 font-bold text-danger">Reject Content Draft</h3>
            <p className="mt-8 text-xs opacity-70">
              Provide feedback on why this draft is rejected so the team or pipeline can revise it.
            </p>
            <textarea
              rows={3}
              value={rejectReason}
              onChange={(e) => setRejectReason(e.target.value)}
              placeholder="e.g. Tone too informal, missed main speaker conclusion..."
              className="mt-13 w-full rounded-card border border-black/10 bg-canvas-light p-13 text-sm dark:border-white/10 dark:bg-canvas-dark"
            />
            <div className="mt-21 flex justify-end gap-13">
              <button
                type="button"
                onClick={() => setShowRejectModal(false)}
                className="rounded-card px-13 py-8 text-xs font-medium hover:bg-black/5 dark:hover:bg-white/5"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={() =>
                  rejectMutation.mutate({
                    id: currentPiece!.id,
                    reason: rejectReason || "Rejected during review",
                  })
                }
                disabled={rejectMutation.isPending}
                className="rounded-card bg-danger px-13 py-8 text-xs font-semibold text-white hover:opacity-90"
              >
                {rejectMutation.isPending ? "Rejecting..." : "Confirm Rejection"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
